### ISSUE TITLE
Add support for PHP 7

### ISSUE THREAD

**Issue by nikic** [nikic/scalar_objects#25]

**Comment by HallofFamer** [comment]
Oh this is interesting, so i see you are developing it for PHP 7 now, and as you said earlier, syntax such as "hello world"->toUpper() and [2, 6, 4, 3]->sort() will be available too(without assigning scalar to a variable first), is this correct?

**Comment by nikic** [comment]
PHP 7 is now supported.

@HallofFamer Yes, that syntax is supported under PHP 7. I added a test for it: https://github.com/nikic/scalar_objects/commit/78110f0cf68b9baa86f12036087627fbed89cd50

**Comment by HallofFamer** [comment]
I see, I recall you mentioned that the reason why the call method upon variable creation syntax is not allowed in PHP 5 is due to the limitation of old PHP parser, which means that the PHP parser has changed since PHP 7, is this the reason? 

Also if scalar objects can exist as an extension(without modifying PHP core files such as zend.c), is it possible to bring it to PECL at first? I actually want to see it in PHP core eventually, but a move to PECL is acceptable at least.
